# Generated by Django 2.2.3 on 2019-07-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='text',
            new_name='content',
        ),
    ]
