# Generated by Django 2.2.3 on 2019-07-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190725_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='reminder_date',
            new_name='reminder',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='is_reminder',
        ),
    ]
