# Generated by Django 2.2.3 on 2019-07-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190725_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='label',
        ),
        migrations.AddField(
            model_name='notes',
            name='labels',
            field=models.ManyToManyField(to='users.Label'),
        ),
    ]
