# Generated by Django 2.2.3 on 2019-08-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteinfo',
            name='is_pin',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
