# Generated by Django 2.2.3 on 2019-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20190807_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
