# Generated by Django 2.2.3 on 2019-08-31 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20190807_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteinfo',
            old_name='is_archived',
            new_name='is_archive',
        ),
        migrations.RenameField(
            model_name='noteinfo',
            old_name='is_pinned',
            new_name='is_pin',
        ),
        migrations.RenameField(
            model_name='noteinfo',
            old_name='is_trashed',
            new_name='is_trash',
        ),
    ]
